# Generated by Django 4.2.2 on 2024-01-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('lat_long', models.CharField(max_length=255)),
                ('full_details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='full_details',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='items',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='lat_long',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='location',
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dish_search.restaurant'),
            preserve_default=False,
        ),
    ]
