# Generated by Django 4.2.2 on 2024-01-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish_search', '0002_restaurant_remove_dish_full_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
